# Generated by Django 5.1.1 on 2024-10-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_timestamp_course_updated_lesson_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='public_id',
        ),
    ]
